from OntologyAutomation import *
import re

# Intoduce clases in list
mainClasses = ['acm_titles','keywords','year'] #[Class, Class, ..]
# Intoduce subclases in list
subClasses = [['information_systems_keywords','keywords'],
              ['computer_methodology_keywords','keywords'],
              ['social_and_behavioral_sciences_keywords','keywords'],
              ['information_search_and_retrieval_keywords','information_systems_keywords'],
              ['distributed_systems_keywords','computer_methodology_keywords'],
              ['distributed_artificial_intelligence_and_multi_agent_systems_keywords','computer_methodology_keywords']]  # [Subclass, ParentClass]
# Introduce properties in list with domain and range
mainProperties = [['has_keyword', 'acm_titles', 'keywords']]  # [Predicate, Subject's Class, Object's Class]
# Introduce word concepts(instances) with classifications


classifiedWords = [['agent_bases_tech', 'acm_titles'],
                   ['agent_id', 'information_search_and_retrieval_keywords'],
                   ['agent_number', 'information_search_and_retrieval_keywords'],
                   ['adptive resource management tool', 'distributed_systems_keywords '],
                   ['distributed real time embedded system', 'distributed_systems_keywords '],
                   ['end-to-end quality of service', 'distributed_systems_keywords '],
                   ['service end-to-end quality', 'distributed_systems_keywords '],
                   ['hybrid adaptive resourcemanagement middleware', 'distributed_systems_keywords '],
                   ['hybrid control technique', 'distributed_systems_keywords '],
                   ['real-time video distribution system', 'distributed_systems_keywords '],
                   ['real-time corba specification', 'distributed_systems_keywords '],
                   ['video encoding/decoding', 'distributed_systems_keywords '],
                   ['resource reservation mechanism', 'distributed_systems_keywords '],
                   ['dynamic environment', 'distributed_systems_keywords '],
                   ['streaming service', 'distributed_systems_keywords '],
                   ['distribute real-time embed system', 'distributed_systems_keywords '],
                   ['hybrid system', 'distributed_systems_keywords '],
                   ['quality of service', 'distributed_systems_keywords '],
                   ['service quality', 'distributed_systems_keywords '],
                   ['ensemble kalman filter', 'distributed_systems_keywords '],
                   ['datum assimilation methodology', 'distributed_systems_keywords '],
                   ['hydrocarbon reservoir simulation', 'distributed_systems_keywords '],
                   ['energy exploration', 'distributed_systems_keywords '],
                   ['tigre grid computing environment', 'distributed_systems_keywords '],
                   ['grid computing', 'distributed_systems_keywords '],
                   ['cyberinfrastructure development project', 'distributed_systems_keywords '],
                   ['high performance computing', 'distributed_systems_keywords '],
                   ['tigre grid middleware', 'distributed_systems_keywords '],
                   ['strategic application area', 'distributed_systems_keywords '],
                   ['gridway metascheduler', 'distributed_systems_keywords '],
                   ['pooling license', 'distributed_systems_keywords '],
                   ['grid-enabling', 'distributed_systems_keywords '],
                   ['reservoir model', 'distributed_systems_keywords '],
                   ['enkf', 'distributed_systems_keywords '],
                   ['tigre', 'distributed_systems_keywords '],
                   ['and gridway', 'distributed_systems_keywords '],
                   ['multi-sequence positioning', 'distributed_systems_keywords '],
                   ['wireless sensor network', 'distributed_systems_keywords '],
                   ['massive uva-based deploment', 'distributed_systems_keywords '],
                   ['node localization', 'distributed_systems_keywords '],
                   ['spatiotemporal correlation', 'distributed_systems_keywords '],
                   ['event distribution', 'distributed_systems_keywords '],
                   ['range-based approach', 'distributed_systems_keywords '],
                   ['distribution-based location estimation', 'distributed_systems_keywords '],
                   ['listen-detect-assemble-report protocol', 'distributed_systems_keywords '],
                   ['marginal distribution', 'distributed_systems_keywords '],
                   ['localization', 'distributed_systems_keywords '],
                   ['node sequence process', 'distributed_systems_keywords '],
                   ['wireless sensor network', 'distributed_systems_keywords '],
                   ['localization', 'distributed_systems_keywords '],
                   ['corner-cube retro-reflector', 'distributed_systems_keywords '],
                   ['performance', 'distributed_systems_keywords '],
                   ['range', 'distributed_systems_keywords '],
                   ['sensor node', 'distributed_systems_keywords '],
                   ['aerial vehicle', 'distributed_systems_keywords '],
                   ['image processing', 'distributed_systems_keywords '],
                   ['scene labeling', 'distributed_systems_keywords '],
                   ['consistency', 'distributed_systems_keywords '],
                   ['probability', 'distributed_systems_keywords '],
                   ['unique mapping', 'distributed_systems_keywords '],
                   ['connectivity', 'distributed_systems_keywords '],
                   ['sensor datum', 'distributed_systems_keywords '],
                   ['separation of datum', 'distributed_systems_keywords '],
                   ['datum separation', 'distributed_systems_keywords '],
                   ['analysis', 'distributed_systems_keywords '],
                   ['archive', 'distributed_systems_keywords '],
                   ['flooding', 'distributed_systems_keywords '],
                   ['geographic hash table', 'distributed_systems_keywords '],
                   ['homogeneous architecture', 'distributed_systems_keywords '],
                   ['multi-tier sensor network', 'distributed_systems_keywords '],
                   ['flash storage', 'distributed_systems_keywords '],
                   ['metada', 'distributed_systems_keywords '],
                   ['distributed index structure', 'distributed_systems_keywords '],
                   ['interval skip graph', 'distributed_systems_keywords '],
                   ['spatial scoping', 'distributed_systems_keywords '],
                   ['interval tree', 'distributed_systems_keywords '],
                   ['wireless sensor network', 'distributed_systems_keywords '],
                   ['archival storage', 'distributed_systems_keywords '],
                   ['index method', 'distributed_systems_keywords '],
                   ['sensor network', 'distributed_systems_keywords '],
                   ['multidimensional range query', 'distributed_systems_keywords '],
                   ['distributed index', 'distributed_systems_keywords '],
                   ['centralized index', 'distributed_systems_keywords '],
                   ['distributed datum structure', 'distributed_systems_keywords '],
                   ['datacentric storage system', 'distributed_systems_keywords '],
                   ['geographic routing', 'distributed_systems_keywords '],
                   ['event insertion', 'distributed_systems_keywords '],
                   ['querying cost', 'distributed_systems_keywords '],
                   ['indexing technique', 'distributed_systems_keywords '],
                   ['query flooding', 'distributed_systems_keywords '],
                   ['efficient correlation', 'distributed_systems_keywords '],
                   ['locality-preserving geographic hash', 'distributed_systems_keywords '],
                   ['asymptotic behavior', 'distributed_systems_keywords '],
                   ['normal event distribution', 'distributed_systems_keywords '],
                   ['dim', 'distributed_systems_keywords '],
                   ['multi-dimensional range query', 'distributed_systems_keywords '],
                   ['routing protocol', 'distributed_systems_keywords '],
                   ['contact trace', 'distributed_systems_keywords '],
                   ['delay-tolerant network', 'distributed_systems_keywords '],
                   ['mobile opportunistic network', 'distributed_systems_keywords '],
                   ['frequent link break', 'distributed_systems_keywords '],
                   ['end-to-end path', 'distributed_systems_keywords '],
                   ['random mobility model', 'distributed_systems_keywords '],
                   ['realistic mobility trace', 'distributed_systems_keywords '],
                   ['unicast', 'distributed_systems_keywords '],
                   ['transfer probability', 'distributed_systems_keywords '],
                   ['direct-delivery protocol', 'distributed_systems_keywords '],
                   ['epidemic protocol', 'distributed_systems_keywords '],
                   ['replication strategy', 'distributed_systems_keywords '],
                   ['history of past encounter and transitivity', 'distributed_systems_keywords '],
                   ['past encounter and transitivity history', 'distributed_systems_keywords '],
                   ['prophet', 'distributed_systems_keywords '],
                   ['opportunistic network', 'distributed_systems_keywords '],
                   ['route', 'distributed_systems_keywords '],
                   ['simulation', 'distributed_systems_keywords '],
                   ['search and rescue', 'distributed_systems_keywords '],
                   ['connected network', 'distributed_systems_keywords '],
                   ['emergency situation', 'distributed_systems_keywords '],
                   ['pervasive computing', 'distributed_systems_keywords '],
                   ['satellite transmitter', 'distributed_systems_keywords '],
                   ['witness', 'distributed_systems_keywords '],
                   ['intermittent network connectivity', 'distributed_systems_keywords '],
                   ['group and partition', 'distributed_systems_keywords '],
                   ['location tracking system', 'distributed_systems_keywords '],
                   ['hiker', 'distributed_systems_keywords '],
                   ['gp receiver', 'distributed_systems_keywords '],
                   ['rf transmitter', 'distributed_systems_keywords '],
                   ['beacon', 'distributed_systems_keywords '],
                   ['sensor network', 'distributed_systems_keywords '],
                   ['fairness', 'distributed_systems_keywords '],
                   ['dead-reckoning vector', 'distributed_systems_keywords '],
                   ['distributed multi-player game', 'distributed_systems_keywords '],
                   ['budget based algorithm', 'distributed_systems_keywords '],
                   ['mean error', 'distributed_systems_keywords '],
                   ['accuracy', 'distributed_systems_keywords '],
                   ['scheduling algorithm', 'distributed_systems_keywords '],
                   ['quantization', 'distributed_systems_keywords '],
                   ['export error', 'distributed_systems_keywords '],
                   ['bucket synchronization', 'distributed_systems_keywords '],
                   ['network delay', 'distributed_systems_keywords '],
                   ['distribute multi-player game', 'distributed_systems_keywords '],
                   ['dead-reckon', 'distributed_systems_keywords '],
                   ['clock synchronization', 'distributed_systems_keywords '],
                   ['local lag', 'distributed_systems_keywords '],
                   ['multiplayer game', 'distributed_systems_keywords '],
                   ['consistency', 'distributed_systems_keywords '],
                   ['network transmission delay', 'distributed_systems_keywords '],
                   ['time warp', 'distributed_systems_keywords '],
                   ['accurate state', 'distributed_systems_keywords '],
                   ['correction', 'distributed_systems_keywords '],
                   ['physical clock', 'distributed_systems_keywords '],
                   ['usability and fairness', 'distributed_systems_keywords '],
                   ['gs-dr-ll', 'distributed_systems_keywords '],
                   ['distribute multi-player game', 'distributed_systems_keywords '],
                   ['continuous replicate application', 'distributed_systems_keywords '],
                   ['dead-reckon', 'distributed_systems_keywords '],
                   ['remote access', 'distributed_systems_keywords '],
                   ['large spatial datum', 'distributed_systems_keywords '],
                   ['client-server architecture', 'distributed_systems_keywords '],
                   ['spatial query evaluation', 'distributed_systems_keywords '],
                   ['datum visualization', 'distributed_systems_keywords '],
                   ['datum management', 'distributed_systems_keywords '],
                   ['centralized peer-to-peer approach', 'distributed_systems_keywords '],
                   ['network latency', 'distributed_systems_keywords '],
                   ['sand', 'distributed_systems_keywords '],
                   ['dynamic network infrastructure', 'distributed_systems_keywords '],
                   ['web browser', 'distributed_systems_keywords '],
                   ['internet-enabled database management system', 'distributed_systems_keywords '],
                   ['gi', 'distributed_systems_keywords '],
                   ['internet', 'distributed_systems_keywords '],
                   ['client/server', 'distributed_systems_keywords '],
                   ['peer-to-peer', 'distributed_systems_keywords '],
                   ['context awareness', 'distributed_systems_keywords '],
                   ['group interaction', 'distributed_systems_keywords '],
                   ['software framework', 'distributed_systems_keywords '],
                   ['contextaware', 'distributed_systems_keywords '],
                   ['mobility system', 'distributed_systems_keywords '],
                   ['fifth contextdimension group-context', 'distributed_systems_keywords '],
                   ['xml configuration file', 'distributed_systems_keywords '],
                   ['event-condition-action', 'distributed_systems_keywords '],
                   ['sensor fusion', 'distributed_systems_keywords '],
                   ['location sense', 'distributed_systems_keywords '],
                   ['process execution', 'distributed_systems_keywords '],
                   ['grid computing', 'distributed_systems_keywords '],
                   ['distributed system', 'distributed_systems_keywords '],
                   ['distributed application', 'distributed_systems_keywords '],
                   ['distributed process', 'distributed_systems_keywords '],
                   ['distributed scheduling', 'distributed_systems_keywords '],
                   ['distributed execution', 'distributed_systems_keywords '],
                   ['distributed computing', 'distributed_systems_keywords '],
                   ['parallel computing', 'distributed_systems_keywords '],
                   ['parallel execution', 'distributed_systems_keywords '],
                   ['process description', 'distributed_systems_keywords '],
                   ['hierarchical process execution', 'distributed_systems_keywords '],
                   ['grid architecture', 'distributed_systems_keywords '],
                   ['scheduling algorithm', 'distributed_systems_keywords '],
                   ['process support', 'distributed_systems_keywords '],
                   ['distribute middleware', 'distributed_systems_keywords '],
                   ['congestion game', 'distributed_systems_keywords '],
                   ['load-dependent failure', 'distributed_systems_keywords '],
                   ['identical resource', 'distributed_systems_keywords '],
                   ['nash equilibrium', 'distributed_systems_keywords '],
                   ['nondecreasing cost function', 'distributed_systems_keywords '],
                   ['localeffect game', 'distributed_systems_keywords '],
                   ['resource cost function', 'distributed_systems_keywords '],
                   ['real-valued function', 'distributed_systems_keywords '],
                   ['potential function', 'distributed_systems_keywords '],
                   ['failure probability', 'distributed_systems_keywords '],
                   ['load-dependent failure', 'distributed_systems_keywords '],
                   ['load-dependent resource failure', 'distributed_systems_keywords '],
                   ['pure strategy nash equilibrium', 'distributed_systems_keywords '],
                   ['information management system', 'distributed_systems_keywords '],
                   ['distributed hash table', 'distributed_systems_keywords '],
                   ['networked system monitoring', 'distributed_systems_keywords '],
                   ['large-scale networked system', 'distributed_systems_keywords '],
                   ['distributed operating system backbone', 'distributed_systems_keywords '],
                   ['read-dominated attribute', 'distributed_systems_keywords '],
                   ['write-dominated attribute', 'distributed_systems_keywords '],
                   ['virtual node', 'distributed_systems_keywords '],
                   ['update-upk-downj strategy', 'distributed_systems_keywords '],
                   ['temporal heterogeneity', 'distributed_systems_keywords '],
                   ['administrative isolation', 'distributed_systems_keywords '],
                   ['autonomous dht', 'distributed_systems_keywords '],
                   ['aggregation management layer', 'distributed_systems_keywords '],
                   ['availability', 'distributed_systems_keywords '],
                   ['eventual consistency', 'distributed_systems_keywords '],
                   ['lazy re-aggregation', 'distributed_systems_keywords '],
                   ['freepastry framework', 'distributed_systems_keywords '],
                   ['tunable spatial replication', 'distributed_systems_keywords '],
                   ['distribute hash table', 'distributed_systems_keywords '],
                   ['network system monitor', 'distributed_systems_keywords '],
                   ['multi-player online game', 'distributed_systems_keywords '],
                   ['communication proxy', 'distributed_systems_keywords '],
                   ['latency compensation', 'distributed_systems_keywords '],
                   ['artificial latency', 'distributed_systems_keywords '],
                   ['proxy-based game architecture', 'distributed_systems_keywords '],
                   ['central-server architecture', 'distributed_systems_keywords '],
                   ['assignment of authority', 'distributed_systems_keywords '],
                   ['authority assignment', 'distributed_systems_keywords '],
                   ['first person shooter', 'distributed_systems_keywords '],
                   ['role playing game', 'distributed_systems_keywords '],
                   ['client authoritative approach', 'distributed_systems_keywords '],
                   ['cheat-proof mechanism', 'distributed_systems_keywords '],
                   ['mmog', 'distributed_systems_keywords '],
                   ['distribute multi-player game', 'distributed_systems_keywords '],
                   ['authority', 'distributed_systems_keywords '],
                   ['smart market', 'distributed_systems_keywords '],
                   ['network monitor', 'distributed_systems_keywords '],
                   ['routing stagequality', 'distributed_systems_keywords '],
                   ['verifiable monitor', 'distributed_systems_keywords '],
                   ['contractible monitor', 'distributed_systems_keywords '],
                   ['contracting system', 'distributed_systems_keywords '],
                   ['commoditization', 'distributed_systems_keywords '],
                   ['routing policy', 'distributed_systems_keywords '],
                   ['clean-slate architectural design', 'distributed_systems_keywords '],
                   ['innovation', 'distributed_systems_keywords '],
                   ['monitor', 'distributed_systems_keywords '],
                   ['contract', 'distributed_systems_keywords '],
                   ['incentive', 'distributed_systems_keywords '],
                   ['wireless sensor network-based mobile countersniper system', 'distributed_systems_keywords '],
                   ['helmetmounted microphone array', 'distributed_systems_keywords '],
                   ['internode communication', 'distributed_systems_keywords '],
                   ['sensorboard', 'distributed_systems_keywords '],
                   ['self orientation', 'distributed_systems_keywords '],
                   ['trajectory', 'distributed_systems_keywords '],
                   ['range', 'distributed_systems_keywords '],
                   ['caliber', 'distributed_systems_keywords '],
                   ['weapon type', 'distributed_systems_keywords '],
                   ['1degree trajectory precision', 'distributed_systems_keywords '],
                   ['caliber estimation accuracy', 'distributed_systems_keywords '],
                   ['sensor network', 'distributed_systems_keywords '],
                   ['datum fusion', 'distributed_systems_keywords '],
                   ['acoustic source localization', 'distributed_systems_keywords '],
                   ['weapon classification', 'distributed_systems_keywords '],
                   ['caliber estimation', 'distributed_systems_keywords '],
                   ['streamlined functionality', 'distributed_systems_keywords '],
                   ['end-to-end workflow composition', 'distributed_systems_keywords '],
                   ['scheduling agent', 'distributed_systems_keywords '],
                   ['service request', 'distributed_systems_keywords '],
                   ['heuristic', 'distributed_systems_keywords '],
                   ['scheduling service', 'distributed_systems_keywords '],
                   ['business process workflow', 'distributed_systems_keywords '],
                   ['business value metric', 'distributed_systems_keywords '],
                   ['multi-tiered system', 'distributed_systems_keywords '],
                   ['multi-organisation environment', 'distributed_systems_keywords '],
                   ['qos-defined limit', 'distributed_systems_keywords '],
                   ['web service', 'distributed_systems_keywords '],
                   ['qo', 'distributed_systems_keywords '],
                   ['workﬂows', 'distributed_systems_keywords '],
                   ['schedule', 'distributed_systems_keywords '],
                   ['visual art', 'distributed_systems_keywords '],
                   ['design', 'distributed_systems_keywords '],
                   ['large-scale integration of technology', 'distributed_systems_keywords '],
                   ['design education', 'distributed_systems_keywords '],
                   ['mac os x', 'distributed_systems_keywords '],
                   ['operating system', 'distributed_systems_keywords '],
                   ['high-end graphic', 'distributed_systems_keywords '],
                   ['nonlinear video editing', 'distributed_systems_keywords '],
                   ['animation', 'distributed_systems_keywords '],
                   ['multimedia', 'distributed_systems_keywords '],
                   ['web production', 'distributed_systems_keywords '],
                   ['digital video application', 'distributed_systems_keywords '],
                   ['xgrid environment', 'distributed_systems_keywords '],
                   ['macintosh os x', 'distributed_systems_keywords '],
                   ['xgrid', 'distributed_systems_keywords '],
                   ['grid computing', 'distributed_systems_keywords '],
                   ['cluster', 'distributed_systems_keywords '],
                   ['highperformance computing', 'distributed_systems_keywords '],
                   ['rendezvous', 'distributed_systems_keywords '],
                   ['render', 'distributed_systems_keywords '],
                   ['audio and video clip', 'distributed_systems_keywords '],
                   ['peer-to-peer vehicular ad-hoc network', 'distributed_systems_keywords '],
                   ['datum carrier', 'distributed_systems_keywords '],
                   ['termed zebroid', 'distributed_systems_keywords '],
                   ['mobile device', 'distributed_systems_keywords '],
                   ['availability latency', 'distributed_systems_keywords '],
                   ['car density', 'distributed_systems_keywords '],
                   ['storage per device', 'distributed_systems_keywords '],
                   ['repository size', 'distributed_systems_keywords '],
                   ['replacement policy', 'distributed_systems_keywords '],
                   ['naive random replacement policy', 'distributed_systems_keywords '],
                   ['zebroid', 'distributed_systems_keywords '],
                   ['simplified instantiation of zebroid', 'distributed_systems_keywords '],
                   ['zebroid simplified instantiation', 'distributed_systems_keywords '],
                   ['mobility', 'distributed_systems_keywords '],
                   ['vehicular network', 'distributed_systems_keywords '],
                   ['automaton', 'distributed_systems_keywords '],
                   ['latency', 'distributed_systems_keywords '],
                   ['markov model', 'distributed_systems_keywords '],
                   ['web application', 'distributed_systems_keywords '],
                   ['mobile wireless pda', 'distributed_systems_keywords '],
                   ['web browser', 'distributed_systems_keywords '],
                   ['functionality', 'distributed_systems_keywords '],
                   ['pthinc', 'distributed_systems_keywords '],
                   ['full-function web browser', 'distributed_systems_keywords '],
                   ['pda thinclient solution', 'distributed_systems_keywords '],
                   ['local pda web browser', 'distributed_systems_keywords '],
                   ['thin-client', 'distributed_systems_keywords '],
                   ['web browsing performance', 'distributed_systems_keywords '],
                   ['video playback', 'distributed_systems_keywords '],
                   ['crucial browser helper application', 'distributed_systems_keywords '],
                   ['high-fidelity display', 'distributed_systems_keywords '],
                   ['seamless mobility', 'distributed_systems_keywords '],
                   ['system usability', 'distributed_systems_keywords '],
                   ['screen resolution', 'distributed_systems_keywords '],
                   ['thin-client computing', 'distributed_systems_keywords '],
                   ['remote display', 'distributed_systems_keywords '],
                   ['mobility', 'distributed_systems_keywords '],
                   ['pervasive web', 'distributed_systems_keywords '],
                   ['sensor-grouping', 'distributed_systems_keywords '],
                   ['point-distribution index', 'distributed_systems_keywords '],
                   ['wireless sensor network', 'distributed_systems_keywords '],
                   ['honeycomb structure', 'distributed_systems_keywords '],
                   ['surveillance', 'distributed_systems_keywords '],
                   ['redundancy', 'distributed_systems_keywords '],
                   ['fault tolerance', 'distributed_systems_keywords '],
                   ['node-deduction process', 'distributed_systems_keywords '],
                   ['incremental coverage quality algorithm', 'distributed_systems_keywords '],
                   ['sleeping configuration protocol', 'distributed_systems_keywords '],
                   ['sensor coverage', 'distributed_systems_keywords '],
                   ['sensor group', 'distributed_systems_keywords '],
                   ['spectrum sensing', 'distributed_systems_keywords '],
                   ['rf interference', 'distributed_systems_keywords '],
                   ['rf spectrum', 'distributed_systems_keywords '],
                   ['cognitive radio', 'distributed_systems_keywords '],
                   ['spectrum allocation', 'distributed_systems_keywords '],
                   ['coordinated sensing', 'distributed_systems_keywords '],
                   ['fm aggregation', 'distributed_systems_keywords '],
                   ['incremental gossip protocol', 'distributed_systems_keywords '],
                   ['opportunistic spectrum sharing', 'distributed_systems_keywords '],
                   ['spatially decaying aggregate', 'distributed_systems_keywords '],
                   ['innetwork aggregation', 'distributed_systems_keywords '],
                   ['coordinate spectrum sense', 'distributed_systems_keywords '],
                   ['gossip protocol', 'distributed_systems_keywords '],
                   ['fm aggregation', 'distributed_systems_keywords '],
                   ['incremental algorithm', 'distributed_systems_keywords '],
                   ['asynchronous messaging middleware', 'distributed_systems_keywords '],
                   ['mobile ad-hoc environment', 'distributed_systems_keywords '],
                   ['epidemic messaging middleware', 'distributed_systems_keywords '],
                   ['message-oriented middleware', 'distributed_systems_keywords '],
                   ['java messaging service', 'distributed_systems_keywords '],
                   ['asynchronous communication', 'distributed_systems_keywords '],
                   ['epidemic protocol', 'distributed_systems_keywords '],
                   ['cross-layering', 'distributed_systems_keywords '],
                   ['application level routing', 'distributed_systems_keywords '],
                   ['group communication', 'distributed_systems_keywords '],
                   ['message orient middleware', 'distributed_systems_keywords '],
                   ['middleware for mobile computing', 'distributed_systems_keywords '],
                   ['mobile ad-hoc network', 'distributed_systems_keywords '],
                   ['context awareness', 'distributed_systems_keywords '],
                   ['distributed intrusion detection system', 'distributed_systems_keywords '],
                   ['heterogeneous intrusion detection system', 'distributed_systems_keywords '],
                   ['grid middleware', 'distributed_systems_keywords '],
                   ['open grid service architecture', 'distributed_systems_keywords '],
                   ['computational grid', 'distributed_systems_keywords '],
                   ['intrusion detection service', 'distributed_systems_keywords '],
                   ['grid intrusion detection architecture', 'distributed_systems_keywords '],
                   ['integration of ids', 'distributed_systems_keywords '],
                   ['ids integration', 'distributed_systems_keywords '],
                   ['gridsim grid simulator', 'distributed_systems_keywords '],
                   ['grid service for intrusion detection', 'distributed_systems_keywords '],
                   ['intrusion detection system', 'distributed_systems_keywords '],
                   ['grid', 'distributed_systems_keywords '],
                   ['system integration', 'distributed_systems_keywords '],
                   ['service-oriented event correlation', 'distributed_systems_keywords '],
                   ['service management', 'distributed_systems_keywords '],
                   ['fault management', 'distributed_systems_keywords '],
                   ['service level agreement', 'distributed_systems_keywords '],
                   ['qos', 'distributed_systems_keywords '],
                   ['customer service management', 'distributed_systems_keywords '],
                   ['service-oriented management', 'distributed_systems_keywords '],
                   ['process management framework', 'distributed_systems_keywords '],
                   ['case-based reasoning', 'distributed_systems_keywords '],
                   ['rule-based reasoning', 'distributed_systems_keywords '],
                   ['event correlation', 'distributed_systems_keywords '],
                   ['distributed computation', 'distributed_systems_keywords '],
                   ['immediate predecessor tracking', 'distributed_systems_keywords '],
                   ['common global memory', 'distributed_systems_keywords '],
                   ['message transfer delay', 'distributed_systems_keywords '],
                   ['vector clock', 'distributed_systems_keywords '],
                   ['tracking causality', 'distributed_systems_keywords '],
                   ['vector timestamp', 'distributed_systems_keywords '],
                   ['transitive reduction', 'distributed_systems_keywords '],
                   ['channel ordering property', 'distributed_systems_keywords '],
                   ['ipt protocol', 'distributed_systems_keywords '],
                   ['checkpointing problem', 'distributed_systems_keywords '],
                   ['relevant event', 'distributed_systems_keywords '],
                   ['immediate predecessor', 'distributed_systems_keywords '],
                   ['control information', 'distributed_systems_keywords '],
                   ['piggybacking', 'distributed_systems_keywords '],
                   ['causality track', 'distributed_systems_keywords '],
                   ['hasse diagram', 'distributed_systems_keywords '],
                   ['message-pass', 'distributed_systems_keywords '],
                   ['timestamp', 'distributed_systems_keywords '],
                   ['smart sensor', 'distributed_systems_keywords '],
                   ['generic event architecture', 'distributed_systems_keywords '],
                   ['temporal constraint', 'distributed_systems_keywords '],
                   ['event channel', 'distributed_systems_keywords '],
                   ['event-based system', 'distributed_systems_keywords '],
                   ['corba', 'distributed_systems_keywords '],
                   ['real-time entity', 'distributed_systems_keywords '],
                   ['sensor and actuator', 'distributed_systems_keywords '],
                   ['sentient object', 'distributed_systems_keywords '],
                   ['dissemination quality', 'distributed_systems_keywords '],
                   ['cortex', 'distributed_systems_keywords '],
                   ['gear architecture', 'distributed_systems_keywords '],
                   ['temporal validity', 'distributed_systems_keywords '],
                   ['soft real-time channel', 'distributed_systems_keywords '],
                   ['event channel', 'distributed_systems_keywords '],
                   ['cosmic middleware', 'distributed_systems_keywords '],
                   ['event-base communication', 'distributed_systems_keywords '],
                   ['sentient computing', 'distributed_systems_keywords '],
                   ['componentbase system', 'distributed_systems_keywords '],
                   ['middleware architecture', 'distributed_systems_keywords '],
                   ['manet', 'distributed_systems_keywords '],
                   ['manet p2p system', 'distributed_systems_keywords '],
                   ['hybrid discovery scheme', 'distributed_systems_keywords '],
                   ['neighbor discovery protocol', 'distributed_systems_keywords '],
                   ['negative feedback', 'distributed_systems_keywords '],
                   ['query packet', 'distributed_systems_keywords '],
                   ['replica invalidation', 'distributed_systems_keywords '],
                   ['validation mesh', 'distributed_systems_keywords '],
                   ['invalidation packet', 'distributed_systems_keywords '],
                   ['manet routing protocol', 'distributed_systems_keywords '],
                   ['route discovery message', 'distributed_systems_keywords '],
                   ['concurrent update', 'distributed_systems_keywords '],
                   ['resource discovery', 'distributed_systems_keywords '],
                   ['mobile ad-hoc network', 'distributed_systems_keywords '],
                   ['relational database', 'distributed_systems_keywords '],
                   ['temporal locality', 'distributed_systems_keywords '],
                   ['database content', 'distributed_systems_keywords '],
                   ['caching dynamic database content', 'distributed_systems_keywords '],
                   ['hash-based technique', 'distributed_systems_keywords '],
                   ['redundancy', 'distributed_systems_keywords '],
                   ['natural chunk boundary', 'distributed_systems_keywords '],
                   ['proxy', 'distributed_systems_keywords '],
                   ['jdbc driver', 'distributed_systems_keywords '],
                   ['resultset object', 'distributed_systems_keywords '],
                   ['bboard benchmark', 'distributed_systems_keywords '],
                   ['read-write operation', 'distributed_systems_keywords '],
                   ['reciperesultset', 'distributed_systems_keywords '],
                   ['content addressable storage', 'distributed_systems_keywords '],
                   ['relational database system', 'distributed_systems_keywords '],
                   ['database cache', 'distributed_systems_keywords '],
                   ['wide area network', 'distributed_systems_keywords '],
                   ['bandwidth optimization', 'distributed_systems_keywords '],
                   ['energy harvesting system', 'distributed_systems_keywords '],
                   ['sensor network', 'distributed_systems_keywords '],
                   ['environmental energy', 'distributed_systems_keywords '],
                   ['harvesting-aware power management', 'distributed_systems_keywords '],
                   ['power management', 'distributed_systems_keywords '],
                   ['performance scaling', 'distributed_systems_keywords '],
                   ['duty cycling rate', 'distributed_systems_keywords '],
                   ['network latency', 'distributed_systems_keywords '],
                   ['sampling frequency', 'distributed_systems_keywords '],
                   ['solar panel', 'distributed_systems_keywords '],
                   ['energy tracking', 'distributed_systems_keywords '],
                   ['energy neutral operation', 'distributed_systems_keywords '],
                   ['storage buffer', 'distributed_systems_keywords '],
                   ['duty cycle', 'distributed_systems_keywords '],
                   ['power scaling', 'distributed_systems_keywords '],
                   ['energy harvest', 'distributed_systems_keywords '],
                   ['low power design', 'distributed_systems_keywords '],
                   ['collaborative document processing', 'distributed_systems_keywords '],
                   ['pervasive document editing and managing system', 'distributed_systems_keywords '],
                   ['text editing', 'distributed_systems_keywords '],
                   ['real-time transaction', 'distributed_systems_keywords '],
                   ['computer supported collaborative work', 'distributed_systems_keywords '],
                   ['business logic layer', 'distributed_systems_keywords '],
                   ['real-time server component', 'distributed_systems_keywords '],
                   ['collaborative layouting', 'distributed_systems_keywords '],
                   ['hierarchical file system', 'distributed_systems_keywords '],
                   ['restriction', 'distributed_systems_keywords '],
                   ['granularity', 'distributed_systems_keywords '],
                   ['character insertion', 'distributed_systems_keywords '],
                   ['pervasive document edit and management system', 'distributed_systems_keywords '],
                   ['computer support collaborative work', 'distributed_systems_keywords '],
                   ['cscw', 'distributed_systems_keywords '],
                   ['collaborative document', 'distributed_systems_keywords '],
                   ['game-theoretic approach', 'distributed_systems_keywords '],
                   ['caching problem', 'distributed_systems_keywords '],
                   ['nash equilibrium', 'distributed_systems_keywords '],
                   ['network topology', 'distributed_systems_keywords '],
                   ['peer-to-peer file system', 'distributed_systems_keywords '],
                   ['remote replica', 'distributed_systems_keywords '],
                   ['demand distribution', 'distributed_systems_keywords '],
                   ['price of anarchy', 'distributed_systems_keywords '],
                   ['anarchy price', 'distributed_systems_keywords '],
                   ['instrumentation server', 'distributed_systems_keywords '],
                   ['primal-dual technique', 'distributed_systems_keywords '],
                   ['social utility', 'distributed_systems_keywords '],
                   ['submodularity', 'distributed_systems_keywords '],
                   ['group strategyproofness', 'distributed_systems_keywords '],
                   ['aggregation effect', 'distributed_systems_keywords '],
                   ['cache', 'distributed_systems_keywords '],
                   ['distribute system', 'distributed_systems_keywords '],
                   ['peer-to-peer system', 'distributed_systems_keywords '],
                   ['game-theoretic model', 'distributed_systems_keywords ']
                   ] # [individual, Class]

# semantic template
relationshipSet = [['agent_bases_tech', 'has_keyword', 'agent_id'],['agent_bases_tech', 'has_keyword', 'agent_number'],['agent_bases_tech', 'has_keyword', 'adptive_resource_management']]  # [Subject, Predicate, Object]

# Restructuring all arrays to support strucuture in owlready
for i,keyed in enumerate(mainClasses):
    mainClasses[i] = str(re.sub('[^a-zA-Z0-9]+', '_', keyed.lower()).rstrip("_"))

for i,keyed in enumerate(subClasses):
    subClasses[i][0] = str(re.sub('[^a-zA-Z0-9]+', '_', keyed[0].lower()).rstrip("_"))
    subClasses[i][1] = str(re.sub('[^a-zA-Z0-9]+', '_', keyed[1].lower()).rstrip("_"))

for i,keyed in enumerate(classifiedWords):
    classifiedWords[i][0] = str(re.sub('[^a-zA-Z0-9]+', '_', keyed[0].lower()).rstrip("_"))
    classifiedWords[i][1] = str(re.sub('[^a-zA-Z0-9]+', '_', keyed[1].lower()).rstrip("_"))

for i,keyed in enumerate(mainProperties):
    mainProperties[i][0] = str(re.sub('[^a-zA-Z0-9]+', '_', keyed[0].lower()).rstrip("_"))
    mainProperties[i][1] = str(re.sub('[^a-zA-Z0-9]+', '_', keyed[1].lower()).rstrip("_"))
    mainProperties[i][2] = str(re.sub('[^a-zA-Z0-9]+', '_', keyed[2].lower()).rstrip("_"))

for i,keyed in enumerate(relationshipSet):
    relationshipSet[i][0] = str(re.sub('[^a-zA-Z0-9]+', '_', keyed[0].lower()).rstrip("_"))
    relationshipSet[i][1] = str(re.sub('[^a-zA-Z0-9]+', '_', keyed[1].lower()).rstrip("_"))
    relationshipSet[i][2] = str(re.sub('[^a-zA-Z0-9]+', '_', keyed[2].lower()).rstrip("_"))


# Instantiate OntologoyMaker Class Object
owl = OntologyMaker()

owl.ClassDefiner(mainClasses)
owl.SubClassDefiner(subClasses)
owl.updateClassifications(classifiedWords)
owl.PropertyDefiner(mainProperties)
owl.relationshipBuilder(relationshipSet)

# Creating Inferenciable classes
class acm_titles(Thing):
    ontology = owl.onto
class keywords(Thing):
    ontology = owl.onto

class computer_methodology_keywords(keywords):
    ontology = owl.onto
class information_systems_keywords(keywords):
    ontology = owl.onto
class social_and_behavioral_sciences_keywords(keywords):
    ontology = owl.onto

class information_search_and_retrieval_keywords(information_systems_keywords):
    ontology = owl.onto

class distributed_artificial_intelligence_and_multi_agent_systems_keywords(computer_methodology_keywords):
    ontology = owl.onto

class distributed_systems_keywords(computer_methodology_keywords):
    ontology = owl.onto

class has_keyword(Property):
    ontology = owl.onto
    domain   = [acm_titles]
    range    = [keywords]

class distributed_systems(acm_titles):
    equivalent_to = [acm_titles & (restriction(has_keyword, SOME, distributed_systems_keywords))]

class information_search_and_retrieval(acm_titles):
    equivalent_to = [acm_titles & (restriction(has_keyword, SOME, information_search_and_retrieval_keywords))]

class social_and_behavioral_sciences(acm_titles):
    equivalent_to = [acm_titles & (restriction(has_keyword, SOME, social_and_behavioral_sciences_keywords))]

class distributed_artificial_intelligence_and_multi_agent_systems(acm_titles):
    equivalent_to = [acm_titles & (restriction(has_keyword, SOME, distributed_artificial_intelligence_and_multi_agent_systems_keywords))]


# ACTIVE THIS TO DO INFERACNE BEFORE SAVING TO ONTOLOGY [will move indiviudals automatically to it's parent classes without protege]
# owl.onto.sync_reasoner()

# print(owl.onto.properties)
# print(owl.onto.classes)
# print(owl.onto.instances)

owl.saveOnto()
